name: Code Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        pip install -r lambda_functions/requirements.txt
        
    - name: Run Black
      run: black --check .
      
    - name: Run isort
      run: isort --check-only --profile black .
      
    - name: Run flake8
      run: flake8 . --max-line-length=88 --extend-ignore=E203

  js-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install JS dependencies
      run: |
        cd lambda_functions/deployed-lambda
        npm install
        npm install -D eslint
        
    - name: Run ESLint
      run: |
        cd lambda_functions/deployed-lambda
        npx eslint . --ext .js,.mjs